services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_autopost_bot.py"
    environment:
      pythonVersion: 3.12.3
